### PR TITLE
add Error and Display impls for `{Decode,Param}Error`

### LINKED ISSUE #9: Implement std::error::Error for error types
This would make it to work with errors in downstream libraries.

### PR DESCRIPTION
**Pull request by bryant**
@jimmycuadra fixes #9

### CODE REVIEW

**Comment by vks** [comment]
Why not merge this?

**Comment by bryant** [comment]
Ah, sorry. I was waiting for a textual response from jummycuadra and totally missed the thumbs-up.

**Comment by quininer** [comment]
@bryant Incidentally, you can release a new version?

**Comment by bryant** [comment]
Yes. Please open a new issue for this.

**Pull request merged**
