### PR TITLE
Allow usage without threadpool

### PR DESCRIPTION
**Pull request by jackpot51**
This allows usage of argon2 on targets without a full libstd.

### CODE REVIEW

**Comment by jackpot51** [comment]
Sure, I can clean it up a lot - just checking if this is desired.

**Comment by bryant** [comment]
go ahead and rebase onto #21.

**Comment by bryant** [comment]
Just out of curiosity: Are you using this in Redox? What kind of parallelism primitives are there instead?

**Comment by jackpot51** [comment]
All parallel features in libstd are available. num_cpus has not been ported, which is why the threadpool crate does not compile on Redox

**Comment by bryant** [comment]
do you mean the num_cpus crate? scoped_threadpool doesn't depend on that.

**Comment by jackpot51** [comment]
In that case, I will retry building with scoped_threadpool

**Comment by jackpot51** [comment]
It looks like the build using scoped_threadpool works fine now.

**Comment by bryant** [comment]
FYI, this feature was added anyway in https://github.com/bryant/argon2rs/commit/b306695bd786a67958fba44b35e7d98139e3e437 . To build without the scoped_threadpool dependency, invoke `cargo build --no-default-features` (the default setting will use threads whenever `lanes > 1`).

**Pull request closed without merging**
